version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
init:
- ps: '[System.IO.File]::AppendAllText("C:\Windows\System32\drivers\etc\hosts", "`n93.184.221.200`tapi.nuget.org")'
before_build:
- ps: dotnet restore
build:
  publish_nuget: true
  verbosity: minimal
before_package:
- ps: dotnet pack /p:Version="$env:APPVEYOR_BUILD_VERSION"
artifacts:
- path: 'src\**\*.nupkg'
