version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: dotnet restore
build:
  publish_nuget: false
  verbosity: minimal
before_package:
- ps: dotnet pack /p:Version="$env:APPVEYOR_BUILD_VERSION"
artifacts:
- path: 'src\**\*.nupkg'
